### PR TITLE
Getting tip-spec to work with the newest quickSpec

### PR DESCRIPTION
**Pull request by solrun**
tip-spec now works with the newest version of quickSpec (and can be used by Hipster).

### CODE REVIEW

**Comment by nick8325** [comment]
Yayyy! Thanks!

**Comment by nick8325** [comment]
I merged it into master BTW.

**Comment by solrun** [comment]
Great, thanks!

Can you give me write access to the repo so I can keep fiddling with stuff
and cleaning up?

**Comment by nick8325** [comment]
Done! (At least you should have got an invitation.)

BTW, conditionals also should now work in tip-spec - any functions returning Bool get automatically used as a predicate.

**Pull request merged**
